---
apiVersion: v1
kind: Secret
metadata:
  name: demo-k8s-secret-fetch-all
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  conjur-map: |-
    "*": "*"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-k8-secrets-fetch-all
  name: demo-k8-secrets-fetch-all
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-k8-secrets-fetch-all
  template:
    metadata:
      labels:
        app: demo-k8-secrets-fetch-all
      annotations:
        conjur.org/debug-logging: "true"
        conjur.org/log-traces: "true"
        conjur.org/secrets-destination: k8s_secrets
        conjur.org/k8s-secrets: demo-k8-secret-fetch-all
    spec:
      serviceAccountName:  {{ .Values.sm_app_service_account }}
      containers:
        - name: app-container
          image: alpine/curl
          imagePullPolicy: Always
          command: ["sleep","infinity"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: conjur-status
              mountPath: /conjur/status
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
          envFrom:
            - secretRef:
                name: demo-k8s-secret-fetch-all
      initContainers:
        - name: cyberark-secrets-provider-for-k8s
          image: 'cyberark/secrets-provider-for-k8s:latest'
          imagePullPolicy: Always
          #command: ["sleep","infinity"]
          volumeMounts:
            - name: conjur-status
              mountPath: /conjur/status
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
            - name: podinfo
              mountPath: /conjur/podinfo
          env:
            - name: DEBUG
              value: "true"
            - name: CONJURAPI_LOG
              value: "stdout"
            - name: JWT_TOKEN_PATH
              value: /var/run/secrets/tokens/jwt
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: sm-configmap
      volumes:
        - name: conjur-status
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
