---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DBName:   bXlhcHBEQg==
stringData:
  conjur-map: |-
    username:  {{ .Values.sm_k8_secret_id_1 }}
    password:  {{ .Values.sm_k8_secret_id_2 }}
